name: rest_client
description: A Dart implementation of the a REST client that supports using an Isolate for decoding.
version: 2.0.1+6
homepage: https://github.com/peiffer-innovations/rest_client

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  http: ^0.13.4
  intl: ^0.17.0
  json_class: ^2.1.2+3
  logging: ^1.0.2
  meta: ^1.7.0
  uuid: ^3.0.5

dev_dependencies:
  test: ^1.20.1
