name: 'rest_client'
description: 'A Dart implementation of the a REST client that supports using an Isolate for decoding.'
version: '2.1.4+1'
homepage: 'https://github.com/peiffer-innovations/rest_client'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  http: '^0.13.4'
  intl: '^0.17.0'
  json_class: '^2.1.2+4'
  logging: '^1.0.2'
  meta: '^1.7.0'
  uuid: '^3.0.6'

dev_dependencies: 
  test: '^1.21.1'

ignore_updates: 
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'term_glyph'
  - 'vector_math'
